version: "3.8"

services:

  #Builds the frontend Docker image and creates the frontend microservice
  gikonyo-yolo-client:
    image: gikonyo14/gikonyo-yolo-client:v1.0.0
    build: ./client
    container_name: gikonyo-yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - gikonyo-yolo-backend
    networks:
      - yolo-net

  #Builds the backend Docker image and creates the backend microservice
  gikonyo-yolo-backend:
    image: 
    build: ./backend
    container_name:
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - 
    networks:
      - yolo-net

  #Database
  app-ip-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - yolo-net
    volumes:
      - type: volume
        source: yolvol
        target: /data/db

  #Network infrastructure
  networks:
  weekfivenet:
    name: weekfivenet
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.0.0/16
  #Volume to persist data
  volumes:
  yolvol:
    driver: local 
