apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: gikonyo-yolo-backend
          image: gikonyo14/gikonyo-yolo-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: "database-service"  
            - name: DATABASE_PORT
              value: "27017"  
            - name: MONGODB_URI
              value: "mongodb://database-service:27017/yolomy"  
